# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_smallsildepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_src', models.CharField(max_length=100, null=True)),
                ('middle_src', models.CharField(max_length=100, null=True)),
                ('big_src', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('des', models.CharField(max_length=100, null=True)),
                ('active_name', models.CharField(max_length=100, null=True)),
                ('active_content', models.CharField(max_length=100, null=True)),
                ('discount_price', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('orig_price', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('self', models.BooleanField()),
                ('cross1', models.BooleanField()),
            ],
        ),
    ]
