# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='des',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
